import {client} from "../../lib/api/apolloClient";
import {ApolloProvider} from "@apollo/client";
import Head from "next/head";
import Moment from "react-moment";
import TextDefault from "../../components/atom/text/TextDefault";
// @ts-ignore
import React from "react";
import {FeedArticles} from "../../components/organism/feed/feedArticles";
import TextH1 from "../../components/atom/text/textH1";

export default function Index()  {
    function audioText(text) {
        const utterance = new SpeechSynthesisUtterance(text);
        //utterance.lang = 'en-US';
        utterance.rate = 0.75;
        speechSynthesis.speak(utterance);
    }

    // Execute JQuery script
    /*if (typeof window === "object") {
        // code is running in a browser environment
        $(document).ready(function() {
            $(window).bind('load', function() {
                let root = window.getComputedStyle(document.body);
                let colorText = $(":root").css("--text-color");
                let colorTextFilter = $(":root").css("--text-color-filter");
                let colorBackground = $(":root").css("--background-color");
                let colorBackgroundFilter = $(":root").css("--background-color-filter");
                let colorContainer = $(":root").css("--container-color");
                //change colors variables
                $(":root").css("--text-color", colorBackground);
                $(":root").css("--text-color-filter", colorBackgroundFilter);
                $(":root").css("--background-color", colorText);
                $(":root").css("--background-color-filter", colorTextFilter);
            });
        });
    } else {
        // code is running in a Node.js environment
    }*/

    if (!client) {
        return <TextDefault>Loading</TextDefault>
    } else {
        return (
            <>
                <Head>
                    <title>Manon Salsou - Jouskaio's portfolio 2022</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <>
                    <ApolloProvider client={client}>
                        <main className={"l-main__o-global l-blog"}>
                            <TextH1 classname={"l-blog__a-title"}>Blog</TextH1>
                            <FeedArticles />
                        </main>
                    </ApolloProvider>
                </>
            </>
        );
    }
}
