import {client} from "../lib/blog/apolloClient";
import {getStrapiMedia} from "../lib/blog/api";
// @ts-ignore
import {ApolloProvider} from "@apollo/client";
import {ArticlesQuery, ArticlesQueryWithPagination} from "../lib/blog/article/articles";
import NavCategories from '../components/molecule/navigation/categories'
import React from "react";
import Header from "../components/organisms/navigation/header";
// @ts-ignore
import Head from "next/head";
// @ts-ignore
import Image from "next/image";
import {shimmer, toBase64} from "../components/protons/preload/preload-image";
import TextH1 from "../components/atom/text/textH1";
import Tag from "../components/molecule/quotes/Tag";
// @ts-ignore
import Moment from "react-moment";
import Button from "../components/atom/button/button";
import TextLink from "../components/atom/text/textLink";
export default class Blog extends React.Component {
    render() {
        if (!client) {
            return <p className={"a-text"}>Loading</p>
        }
        return (
            <>
                {/* Initialize Effect */}
                {/*{scroll.scroll}*/}
                <Head>
                    <title>Manon Salsou - Jouskaio's portfolio 2022</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <>
                    <ApolloProvider client={client}>
                        <main className={"l-blog"}>
                            <Header/>
                            <nav className={"l-blog__a-sizeSection l-blog__m-categories"}><NavCategories/></nav>
                            <div className={"l-blog__a-sizeSection l-blog__o-articlesContainer"}>
                                <ArticlesQuery start={0} offset={1}>
                                    {({data: {articles}}) => {
                                        if (parseInt(articles.data.length) == 1) {
                                            let mainArticle = articles.data[0]
                                            return (
                                                <div className={"l-blog__o-mainArticles"}>
                                                    <div className={"l-blog__m-mainArticle"}>
                                                        <div className={"l-blog__m-mainInformations"}>
                                                            <nav>
                                                                <p>{mainArticle.attributes.number}</p>
                                                            </nav>
                                                            <div className={"l-blog__a-mainInformationsLabel"}>
                                                                <p>{mainArticle.attributes.location}</p>
                                                                <p>
                                                                    <Moment format={"LL"}>
                                                                        {mainArticle.attributes.updatedAt}
                                                                    </Moment>
                                                                </p>
                                                            </div>
                                                        </div>
                                                        <TextH1>{mainArticle.attributes.title}</TextH1>
                                                        <div className={"l-blog__m-mainCategory"}>
                                                            -
                                                            {mainArticle.attributes.categories.data.map(function (categorie, i) {
                                                                return <TextLink key={i} classname={"l-blog__m-mainCategory"} src={"/blog/category/"+categorie.attributes.slug}>{categorie.attributes.name}</TextLink>
                                                            })}
                                                            -
                                                        </div>
                                                        <p className={"l-blog__a-mainDesc"}>
                                                            {mainArticle.attributes.description}
                                                        </p>
                                                        <div className={"l-blog__m-mainTags"}>
                                                            {mainArticle.attributes.tags.data.map(function (tag, i) {
                                                                return <Tag key={i} content={tag.attributes.name}
                                                                            color={tag.attributes.color}
                                                                            classname={undefined}/>
                                                            })}
                                                        </div>
                                                        <Button src={"/blog/article/" + mainArticle.attributes.slug} classname={"l-blog__m-buttonArticles"}>See
                                                            article</Button>
                                                    </div>
                                                    <nav className={"l-blog__a-mainImage"}><img
                                                        src={getStrapiMedia(mainArticle.attributes.image)}
                                                        placeholder="blur"
                                                        onLoad={() => `data:image/svg+xml;base64,${toBase64(shimmer("100%", "100%"))}`}
                                                        alt={"Main image"}></img></nav>
                                                </div>
                                            )
                                        } else {
                                            return (<div
                                                className={"l-blog__a-sizeSection l-blog__o-articlesContainer--noArticle"}>Sorry,
                                                there is actually no article for now... :/</div>)
                                        }
                                    }}
                                </ArticlesQuery>
                                {/*@ts-ignore */}
                                <ArticlesQueryWithPagination/>
                            </div>
                        </main>
                    </ApolloProvider>
                </>
            </>
        );
    }
}
